server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mqueen?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT&useSSL=false
    username: zhou
    password: zhou630415
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    timeout: 0
  thymeleaf:
    cache: false
    encoding: UTF-8
    enabled: true
    prefix: classpath:/templates/
  velocity:
    resource-loader-path: classpath:/templates/
    charset: UTF-8
  mail:
    host: smtp.163.com
    username: zhounan328@163.com
    password: zhounan328love
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true