server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mqueen?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT&useSSL=false
    username: zhou
    password: zhou630415